#!/usr/bin/env python3

import os
import subprocess as sp

if __name__ == '__main__':

    commands = {
        'Suspend/Sleep': 'systemctl suspend',
        'Hibernate': 'systemctl hibernate',
        'Reboot/Restart': 'systemctl reboot',
        'Shutdown/Poweroff': 'systemctl poweroff',
    }

    if 'LOCKPRG' in os.environ:
        commands['Lock'] = os.environ['LOCKPRG']

    if 'EXITPRG' in os.environ:
        commands['Exit'] = os.environ['EXITPRG']

    options = commands.keys()
    title = 'rofi-power'
    rofi = f'rofi -dmenu -i -p {title}'.split()
    rofi_input = '\n'.join(x for x in options)

    cp = sp.run(rofi, input=rofi_input, encoding='utf-8', capture_output=True)
    if cp.returncode == 0:
        selection = cp.stdout.strip()
        if selection in commands:
            sp.run(commands[selection].split())
