#!/usr/bin/env python3

import subprocess as sp
import sys

if __name__ == '__main__':

    commands = {
        'Suspend': 'systemctl suspend',
        'Restart': 'systemctl reboot',
        'Shutdown': 'systemctl poweroff',
    }

    if len(sys.argv) > 1:
        commands['Lock'] = sys.argv[1]

    options = commands.keys()
    title = 'rofi-power'
    rofi = f'rofi -dmenu -i -p {title}'.split()
    rofi_input = '\n'.join(x for x in options)

    try:
        selection = sp.check_output(
            rofi, input=rofi_input, encoding='utf-8').strip()
        if selection in commands:
            sp.run(commands[selection].split())
    except sp.CalledProcessError:
        pass
